// GENERATED by scripts/generate-logos.mjs — do not edit.
//
// scale — equalises rendered AREA across marks whose aspect ratios differ, because an
//   <img> box fits a mark with `meet`: 20 px of box gives a wide mark 20×14 of ink and a
//   tall one 13×20, which is most of what makes a row of logos look amateur.
// invert — true only for a mark that is one dark colour, which is the set that disappears
//   on a dark surface. Safe there and nowhere else: inverting a multi-colour mark would
//   render a negative of somebody's logo. Derivations are in the generator.
export type LogoMetric = { scale: number; invert: boolean }

export const LOGO_METRICS: Record<string, LogoMetric> = {
  "tiktok": {
    "scale": 1.064,
    "invert": false
  },
  "instagram": {
    "scale": 1,
    "invert": false
  },
  "youtube": {
    "scale": 1.193,
    "invert": false
  },
  "linkedin": {
    "scale": 1,
    "invert": false
  },
  "facebook": {
    "scale": 1,
    "invert": false
  },
  "twitch": {
    "scale": 1.08,
    "invert": false
  },
  "pinterest": {
    "scale": 1,
    "invert": false
  },
  "snapchat": {
    "scale": 1,
    "invert": false
  },
  "chatgpt": {
    "scale": 1.008,
    "invert": true
  },
  "claude": {
    "scale": 1.002,
    "invert": false
  },
  "perplexity": {
    "scale": 1,
    "invert": false
  },
  "gemini": {
    "scale": 1.003,
    "invert": false
  },
  "google": {
    "scale": 1.011,
    "invert": false
  },
  "bing": {
    "scale": 1.231,
    "invert": false
  },
  "duckduckgo": {
    "scale": 1,
    "invert": false
  },
  "spotify": {
    "scale": 1,
    "invert": false
  },
  "reddit": {
    "scale": 1,
    "invert": false
  },
  "discord": {
    "scale": 1.134,
    "invert": false
  },
  "slack": {
    "scale": 1.001,
    "invert": false
  },
  "github": {
    "scale": 1,
    "invert": true
  },
  "notion": {
    "scale": 1.023,
    "invert": false
  },
  "whatsapp": {
    "scale": 1.003,
    "invert": false
  },
  "telegram": {
    "scale": 1,
    "invert": false
  },
  "x": {
    "scale": 1,
    "invert": true
  },
  "producthunt": {
    "scale": 1,
    "invert": false
  },
  "xiaohongshu": {
    "scale": 1,
    "invert": false
  },
  "apple-podcasts": {
    "scale": 1,
    "invert": false
  },
  "hackernews": {
    "scale": 1,
    "invert": false
  },
  "substack": {
    "scale": 1,
    "invert": false
  },
  "medium": {
    "scale": 1,
    "invert": true
  },
  "quora": {
    "scale": 1,
    "invert": false
  },
  "wechat": {
    "scale": 1,
    "invert": false
  },
  "line": {
    "scale": 1,
    "invert": false
  }
}
